var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "  @                                       X                  X                    ",
   "                             X                                                  ",
   "                 o                                     u                        ",
   "                 x                                o                             ",
   "                     x     o                         u e          xVx           ",
   "                           x                     x   xxx     xx  xx!xx         ",
   "                                x    o         x     x!x         x!!!x          ",
   "                                                      k          xx!xx          ",
   "     o               xx             x  xxxxx                      xkx           ",
   "  xx            u    k                      o o                                x  ",
   "  x      x                 o                                                    x  ",
   "  x   x    x    e                           xxxxx                             ox ",
   "  x          xxxx       o               x               X                      x  ",
   "  x          x!!x                                               xxxxx       x    ",
   "  xxxxx xxxxxxxxxxxxx  xxx  xx    xxxxxx xxx     xxxx     xxxxxxx   xxxxxxxxx  ",
   "                                                    x     x                    ",
   "                                                                                ",
   "       v              v   v     v                     v                             ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! "],
  ["                                                                                                                 ",
   "                                                                                                                 ",
   "   @                                                                                                             ",
   "                                                                                                                 ",
   "                            u                                                                                    ",
   "   x                                                                                                             ",
   "        x                  e                                                                                     ",
   "               o         xxxx                         xvx                                                        ",
   "               x                                                                                                 ",
   "                                                              xx!!!!!!!!!!!xx            v                       ",
   "                  x                                             xxxx!!!!!xxxx                                    ",
   "                                               x                  xxkkkkkx        xxx         xxx                ",
   "                                               x                                x x         x x                  ",
   "                                               ux                                  x                             ",
   "                                               x                                   xx        x                   ",
   "                         x                     xx                                  x         x                   ",
   "                                               ux            o  o          u                                     ",
   "               xxxxxxx        xxx   xxx         x                         ue                                     ",
   "  o           xx     xx        x    x           x           x          xxxxxx       x                            ",
   "  x           xx               x o   x          x                         x!!x               x                   ",
   "         o            ue       x     x          x=        0      x       x!!x         o          x               ",
   "    xxx  x   xxxxxxxxxxx       x     x          x        xx               xxxxx    xxxxxx      x                 ",
   "    x x v  v x         x      xx o   xx         x                    x     o       x         x                   ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x          x   x         x                  ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxxxxx        xx                  ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                    ",
   "!!!!x x!!!!!!x         x!!!!!=                     xx!!!!!!xx  !                     xxxxxxx                     ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                 ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                 ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !!!!!!!!!!!!!!!!!                               "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
